apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-rhoai-operator
  namespace: jh-project-shared
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: redhat-ods-applications
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: redhat-ods-operator
  podSelector: {}
  policyTypes:
  - Ingress
