apiVersion: infrastructure.opendatahub.io/v1
kind: HardwareProfile
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/tracking-id: openshift-ai-operator:infrastructure.opendatahub.io/HardwareProfile:redhat-ods-applications/nvidia-gpu-notebooks
    opendatahub.io/dashboard-feature-visibility: '["workbench"]'
    opendatahub.io/description: ''
    opendatahub.io/disabled: 'false'
    opendatahub.io/display-name: nvidia-gpu
  name: nvidia-gpu-notebooks
  namespace: redhat-ods-applications
spec:
  identifiers:
  - defaultCount: '1'
    displayName: CPU
    identifier: cpu
    maxCount: '8'
    minCount: '1'
    resourceType: CPU
  - defaultCount: 8Gi
    displayName: Memory
    identifier: memory
    maxCount: 32Gi
    minCount: 2Gi
    resourceType: Memory
  - defaultCount: 1
    displayName: nvidia.com/gpu
    identifier: nvidia.com/gpu
    maxCount: 1
    minCount: 1
  scheduling:
    node:
      tolerations:
      - effect: NoSchedule
        key: nvidia-gpu-only
        operator: Exists
        value: ''
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
        value: ''
    type: Node
