apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: s3
  name: s3-config
  namespace: jh-project-shared
data:
  RUSTFS_ADDRESS: ":9000"
  RUSTFS_CONSOLE_ADDRESS: ":9001"
  RUSTFS_CONSOLE_ENABLE: "true"
  RUSTFS_OBS_LOG_DIRECTORY: "/logs"
  RUSTFS_OBS_LOGGER_LEVEL: "info"
  RUSTFS_OBS_ENVIRONMENT: "production"
  RUSTFS_REGION: "us-east-1"
  RUSTFS_VOLUMES: "/data"
