apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-data
  namespace: jh-project-shared
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem
  volumeName: pvc-2c0c90ba-ba5b-4e91-b93e-56e825a60d0f
