apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rustfs-s3
  labels:
    app: rustfs
spec:
  to:
    kind: Service
    name: rustfs-s3
  port:
    targetPort: s3
  tls:
    termination: edge
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rustfs-console
  labels:
    app: rustfs
spec:
  to:
    kind: Service
    name: rustfs-console
  port:
    targetPort: console
  tls:
    termination: edge
