apiVersion: v1
kind: Service
metadata:
  labels:
    app: s3
  name: s3
  namespace: jh-project-shared
spec:
  clusterIP: 172.30.185.106
  clusterIPs:
  - 172.30.185.106
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: api
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: console
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: s3
  sessionAffinity: None
  type: ClusterIP
