apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: pipelines-definition
  namespace: jh-project
spec:
  apiServer:
    artifactSignedURLExpirySeconds: 60
    caBundleFileMountPath: ''
    caBundleFileName: ''
    cacheEnabled: true
    deploy: true
    enableOauth: true
    enableSamplePipeline: false
    pipelineStore: database
  database:
    disableHealthCheck: false
    mariaDB:
      deploy: true
      pipelineDBName: mlpipeline
      pvcSize: 10Gi
      username: mlpipeline
  dspVersion: v2
  objectStorage:
    disableHealthCheck: false
    enableExternalRoute: false
    externalStorage:
      basePath: ''
      bucket: pipeline-artifacts
      host: rustfs-s3.jh-project-shared.svc.cluster.local
      port: '9000'
      region: us-east-1
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: aws-connection-pipeline-s3
      scheme: http
  persistenceAgent:
    deploy: true
    numWorkers: 2
  podToPodTLS: true
  scheduledWorkflow:
    cronScheduleTimezone: UTC
    deploy: true
