apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-quota-gpu
  namespace: jh-project
spec:
  hard:
    limits.cpu: '16'
    limits.memory: 64Gi
    limits.nvidia.com/gpu: '1'
    pods: '20'
    requests.cpu: '8'
    requests.memory: 16Gi
    requests.nvidia.com/gpu: '1'
