apiVersion: v1
kind: LimitRange
metadata:
  name: tenant-limits
  namespace: jh-project
spec:
  limits:
  - default:
      cpu: '2'
      memory: 4Gi
    defaultRequest:
      cpu: 500m
      memory: 512Mi
    max:
      cpu: '16'
      memory: 64Gi
    min:
      cpu: 10m
      memory: 15Mi
    type: Container
