apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jh-workbench-pvc
  namespace: jh-project
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3-csi-immediate
  volumeMode: Filesystem
