apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-tenants
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: tenant-jh-project
          path: tenants/jh-project
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: tenant-jh-project-shared
          path: tenants/jh-project-shared
